### ISSUE TITLE
pay [player] [amount]

### ISSUE THREAD

**Issue by KoenMulder** [KoenMulder/BoxEconomy#4]
on console, the following error appears:

> pay Starscream350 100
> [11:42:45 WARN]: Unexpected exception while parsing console command "pay Starscr
> eam350 100"
> org.bukkit.command.CommandException: Unhandled exception executing command 'pay'
>  in plugin BoxEconomy v0.2
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[cra
> ftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
> 0) ~[craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServe
> r.java:701) ~[craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092
> jnks]
>         at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchServerCommand(Craf
> tServer.java:688) [craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-
> b3092jnks]
>         at net.minecraft.server.v1_7_R3.DedicatedServer.aB(DedicatedServer.java:
> 296) [craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:2
> 61) [craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:5
> 58) [craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java
> :469) [craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:6
> 28) [craftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
> Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R3.command.
> ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
>         at io.github.KoenMulder.BoxEconomy.Main.onCommand(Main.java:45) ~[?:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[cra
> ftbukkit-1.7.9-R0.2.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
>         ... 8 more

**Comment by arselzer** [comment]
fixed in e849f5402bbbeadc2cdce0f1750528e555281730
